name: Update GitHub Activity

on:
  # Se ejecuta automáticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Te permite ejecutarlo manualmente cuando quieras
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Actualizar README con actividad reciente
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Puedes poner el número máximo de eventos que quieres que salgan (ej: 5)
          MAX_LINES: 5
